#!/bin/bash
OS=armv7hf
[[ "$HOSTTYPE" == "x86_64" ]] && OS=amd64
docker container prune -f
docker build -t xptsp/pivpn:${OS}-v2 .
docker images | grep "<none>" | (while read a b c d; do docker rmi $c; done)

