name: Publish to Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish pivpn to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: xayon/pivpn-docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
